sudo: false
language: node_js
services: mongodb
node_js:
  - node
  - '6'
  - '4'
addons:
  code_climate:
    repo_token: db77b58022717b6f1287d1af327a41a58064dfd0b80cf37ecb5e67a866607c83
before_script:
  - 'npm install -g codeclimate-test-reporter'
after_script:
  - 'codeclimate-test-reporter < coverage/lcov.info'
notifications:
  email: false
  slack:
    rooms:
      secure: ltXCdo0rpead7PVIy2v5BjQDhSIZ3dPOX4sZKJwIg0H8SAeVaDjh2EgogV5/yQVhkX2V8UmFJKHVTFuEU7iUgZf5rsInxPBPNSIk13ICVcCZskBiB/XvEfyAOZg1JIMbMz4VFlN9t2iOAh8dCEXAH/MG3EAHuqueUCJLQ9Oyqw8=
